# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{janitor}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Harvey", "Michael Krisher"]
  s.date = %q{2010-09-04}
  s.description = %q{ever leave a breakpoint in your code and do a deploy? not good, right? maybe you just want to remove the logger.info calls from your Rails project. janitor cleans your code.}
  s.email = %q{mike@mikekrisher.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.mdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "janitor.gemspec",
     "lib/janitor.rb",
     "lib/janitor/finder.rb",
     "lib/janitor/janitor.rb",
     "lib/janitor/rak_result.rb",
     "lib/janitor/tasks.rb",
     "lib/tasks/tasks.rake",
     "nails/init.rb",
     "spec/lib/finder_spec.rb",
     "spec/lib/janitor_spec.rb",
     "spec/lib/rak_result_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tjh/janitor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{janitor scans your code for leftover debug statements, console.logs, and vulgarity}
  s.test_files = [
    "spec/lib/finder_spec.rb",
     "spec/lib/janitor_spec.rb",
     "spec/lib/rak_result_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rak>, [">= 0"])
    else
      s.add_dependency(%q<rak>, [">= 0"])
    end
  else
    s.add_dependency(%q<rak>, [">= 0"])
  end
end

